### ISSUE TITLE
Stopping selenium-server doesn't work very well

### ISSUE THREAD

**Issue by josephtate** [floreal/selenium-server-deb-package#3]
Seems to always fall back to the force_stop block, which is overly complicated and kills too many things.

I changed the selenium server user to "jenkins" so that jenkins user could reap stuck chromedriver/chrome browser processes, but every time I stopped selenium-server, jenkins was dying too.

I did some digging and came up with this patch, which uses pkill and pgrep instead of ps | grep to figure out what's still running and killing the leftovers. This does not touch the running jenkins process.

```
diff --git a/src/etc/init.d/selenium-server b/src/etc/init.d/selenium-server
index e104b38..f880cc4 100755
--- a/src/etc/init.d/selenium-server
+++ b/src/etc/init.d/selenium-server
@@ -23,6 +23,7 @@ SCRIPTNAME=/etc/init.d/$NAME
 
 DAEMON=/usr/bin/daemon
 DAEMON_ARGS="--name=$NAME --inherit --env=SELENIUM_HOME=$SELENIUM_HOME --output=$SELENIUM_LOG --pidfile=$PIDFILE"
+PGREP_REGEXP="$SELENIUM_JAR|Xvfb|xvfb-run"
 
 SU=/bin/su
 # Exit if the package is not installed
@@ -99,14 +100,14 @@ do_start()
 # 
 get_running() 
 {
-    return `ps -U $SELENIUM_USER --no-headers -f | egrep -e '(xvfb-run|Xvfb|java|daemon)' | grep -c . `
+    return `pgrep -c -f "$PGREP_REGEXP"`
 }
 
 force_stop() 
 {
     get_running
     if [ $? -ne 0 ]; then 
-        killall -u $SELENIUM_USER Xvfb xvfb-run java daemon || return 3
+        pkill -U $SELENIUM_USER -f "$PGREP_REGEXP" || return 3
     fi
 }
 
@@ -129,6 +130,7 @@ do_stop()
     get_daemon_status 
     case "$?" in
         0) 
+            #THIS DOES NOTHING?!
             $DAEMON $DAEMON_ARGS --stop || return 2
         # wait for the process to really terminate
         for n in 1 2 3 4 5; do
```

I was not able to figure out why the $DAEMON --stop command was not doing anything, but I bet it has to do with the way the init script is using su -l -u <user> -c $DAEMON... to start which makes the process group worthless.

**Comment by floreal** [comment]
That's a very good point. I didn't foresee someone would like to make $SELENIUM_USER running other jvm than selenium-server.
Would you make a PR so that I can let you enjoy the paternity of that contribution ?

**Comment by floreal** [comment]
Thanks. Your contribution is really appreciated
